# Generated by Django 5.0.4 on 2024-05-30 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KhachHang",
            fields=[
                (
                    "MaKH",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("TenKH", models.CharField(max_length=100)),
                ("SDT", models.CharField(max_length=20)),
                ("Email", models.CharField(max_length=100)),
                ("DiaChi", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Kho",
            fields=[
                (
                    "MaKho",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("TenKho", models.CharField(max_length=100)),
                ("DiaChiKho", models.CharField(max_length=100)),
                ("SDT", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Loai",
            fields=[
                (
                    "MaLoai",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("TenLoai", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="NhaCungCap",
            fields=[
                (
                    "MaNCC",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("TenNCC", models.CharField(max_length=100)),
                ("DiaChi", models.CharField(max_length=100)),
                ("Email", models.CharField(max_length=100)),
                ("SDT", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="NhanVien",
            fields=[
                (
                    "MaNV",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("TenNV", models.CharField(max_length=100)),
                ("SDT", models.CharField(max_length=20)),
                ("Email", models.CharField(max_length=100)),
                ("DiaChi", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="HoaDon",
            fields=[
                (
                    "MaHD",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("NgayMua", models.DateField()),
                ("TongTien", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "MaKH",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="TraiCay.khachhang",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhieuNhapHang",
            fields=[
                (
                    "MaPNH",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("NgayNhap", models.DateField()),
                ("TongTien", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "MaNCC",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="TraiCay.khachhang",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SanPham",
            fields=[
                (
                    "MaSP",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("TenSP", models.CharField(max_length=100)),
                ("DonGia", models.DecimalField(decimal_places=2, max_digits=10)),
                ("MoTa", models.TextField()),
                (
                    "MaLoai",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="TraiCay.loai",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HinhAnhSP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("HinhAnh", models.TextField()),
                (
                    "SanPham",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TraiCay.sanpham",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChiTietPhieuNhap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DonGia", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "MaPNH",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="TraiCay.phieunhaphang",
                    ),
                ),
                (
                    "MaSP",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="TraiCay.sanpham",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChiTietKho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SoLuongTon", models.IntegerField(default=0)),
                ("NgayHetHan", models.DateField()),
                (
                    "MaKho",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="TraiCay.kho",
                    ),
                ),
                (
                    "MaSP",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="TraiCay.sanpham",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChiTietHoaDon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SoLuong", models.IntegerField(default=0)),
                ("DonGia", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "MaHD",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="TraiCay.hoadon",
                    ),
                ),
                (
                    "MaSP",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="TraiCay.sanpham",
                    ),
                ),
            ],
        ),
    ]
