# Generated by Django 4.2.11 on 2024-06-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraiCay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HinhAnh', models.TextField()),
                ('Link', models.TextField()),
            ],
        ),
    ]
