# Generated by Django 4.2.11 on 2024-06-03 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TraiCay', '0004_remove_hoadon_tongtien_hoadon_trangthai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giohang',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
