# Generated by Django 4.2.11 on 2024-06-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TraiCay', '0005_alter_giohang_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitietkho',
            name='NgayHetHan',
        ),
    ]
