# Generated by Django 4.2.11 on 2024-06-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TraiCay', '0006_remove_chitietkho_ngayhethan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoadon',
            name='TrangThai',
        ),
    ]
