# Generated by Django 4.2.11 on 2024-06-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraiCay', '0007_remove_hoadon_trangthai'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='TrangThai',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
