# Generated by Django 4.2.11 on 2024-06-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraiCay', '0008_hoadon_trangthai'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='DiaChiGiao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='PhuongThucThanhToan',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='TongTien',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
