# Generated by Django 4.2.11 on 2024-06-04 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TraiCay', '0009_hoadon_diachigiao_hoadon_phuongthucthanhtoan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phieunhaphang',
            name='MaNCC',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TraiCay.nhacungcap'),
        ),
    ]
