# Generated by Django 4.2.11 on 2024-06-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraiCay', '0010_alter_phieunhaphang_mancc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loai',
            name='TenLoai',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='TenSP',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
